from handler import Handler
from mainpage import MainPage
from postpage import PostPage
from commentpage import CommentPage
from newpost import NewPost
from editpost import EditPost
from deletepost import DeletePost
from likearticle import LikeArticle
from editcomment import EditComment
from deletecomment import DeleteComment
from signup import Signup
from register import Register
from login import Login
from logout import Logout	
from welcome import Welcome